[project]
name = "mcp_framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "dotenv>=0.9.9",
    "fastmcp>=2.11.1",
    "langchain-mcp-adapters>=0.1.9",
    "oracledb>=3.3.0",
]
