-- 1. EMS_EQUIPMENT definition

CREATE TABLE "EMS_EQUIPMENT" 
   (    "EQUIPMENT_ID" VARCHAR2(50) NOT NULL ENABLE, 
    "EQUIPMENT_NAME" VARCHAR2(200) NOT NULL ENABLE, 
    "EQUIPMENT_TYPE" VARCHAR2(100) NOT NULL ENABLE, 
    "LOCATION_ID" VARCHAR2(50), 
    "INSTALL_DATE" DATE, 
    "STATUS" VARCHAR2(20) DEFAULT 'ACTIVE', 
    "MAX_CAPACITY" NUMBER(12,3), 
    "UNIT" VARCHAR2(20), 
    "LAST_MAINTENANCE" DATE, 
    "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
    "UPDATED_AT" TIMESTAMP (6), 
     CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')) ENABLE, 
     CONSTRAINT "PK_EMS_EQUIPMENT" PRIMARY KEY ("EQUIPMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;